NANOSECONDS = 1
MICROSECONDS = 1000 * NANOSECONDS
MILLISECONDS = 1000 * MICROSECONDS
SECONDS = 1000 * MILLISECONDS

MINE_RATE = 10*SECONDS

STARTING_BALANCE = 0
MAIN_WALLET_STARTING_BALANCE = 10000

MINING_REWARD = 0
MINING_REWARD_INPUT = { 'address': '*--official-mining-reward--*' }
